version: '3.7'

services:
  etl:
    build: 
      context: ./
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user: root
    volumes:
      - ./workspace:/src/workspace
